#facebook:
#    client:
#        clientId: clientIdTest
#        clientSecret: clientSecretTest
#        accessTokenUri: https://graph.facebook.com/oauth/access_token
#        userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#        tokenName: oauth_token
#        authenticationScheme: query
#        clientAuthentionScheme: form
#        scope: email
#    resource:
#        userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link
        
#google:
#    client:
#        clientId: clientIdTest
#        clientSecret: clientSecretTest
#        accessTokenUri: https://account.google.com/o/oauth2/token
#        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#        scope: email, profile
#    resource:
#      userInfoUri: https://www.googleleaps.com/oauth2/v2/userinfo
      
#kakao:
#    client:
#        clientId: clientIdTest
#        accessTokenUri: https://kauth.kakao.com/oauth/token
#        userAuthorizationUri: https://kauth/kakao.com/oauth/authorize
#    resource:
#        userInfoUri: https://kapi.kakao.com/v1/user/mve

spring:
    thymeleaf:
        cache: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: clientIdTest
                        client-secret: clientSecretTest
                    facebook:
                        client-id: clientIdTest
                        client-secret: clientSecretTest
custom:
    oauth2:
        kakao:
          client-id: clientIdTest